/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */



#include<stdio.h>
#define set(reg,bit)      reg|=(1<<bit)
#define clr(reg,bit)      reg&=~(1<<bit)
#define toggle(reg,bit)   reg^=(1<<bit)
#define RCC_BASE 0x40021000
#define GPIOA_BASE 0x40010800
#define EXTI_BASE 0x40010400
#define AFIO_BASE 0x40010000

#define RCC_APB2ENR *((volatile unsigned int*) (RCC_BASE+0x18))
#define GPIOA_CRH *((volatile unsigned int*)(GPIOA_BASE+0x04))
#define GPIOA_ODR *((volatile unsigned int*)(GPIOA_BASE+0x0c))
#define RCC_CR *((volatile unsigned int*)(RCC_BASE+0x00))
#define RCC_CFGR *((volatile unsigned int*)(RCC_BASE+0x04))
#define RCC_IOPAEN 2
#define GPIOA13 13

void clock_init()
{
	//Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	RCC_CFGR |= (0b100)<<11 ;
	//Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
	RCC_CFGR |= (0b100)<<8 ;
	//Bit 2 IOPAEN: IO port A clock enable
	set(RCC_APB2ENR,RCC_IOPAEN);
}
int main ()
{
	clock_init();

	GPIOA_CRH &=0xff0fffff;
	GPIOA_CRH |=0x00200000;
	while(1)
	{
		set(GPIOA_ODR,GPIOA13);
		for(int i=0;i<5000;i++);
		clr(GPIOA_ODR,GPIOA13);
		for(int i=0;i<5000;i++);
	}
}
