/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#define READ_bit(reg,bit) ((reg & 1<<bit)>>bit)
#define Toggle_bit(reg,bit)   reg^=(1<<bit)
//GPIO registers
#define GPIOA_BASE 0x40010800
#define GPIOB_BASE 0x40010C00

#define GPIOB_CRL *((volatile unsigned int*)(GPIOB_BASE+0x00))
#define GPIOB_CRH *((volatile unsigned int*)(GPIOB_BASE+0x04))
#define GPIOB_IDR *((volatile unsigned int*)(GPIOB_BASE+0x08))
#define GPIOB_ODR *((volatile unsigned int*)(GPIOB_BASE+0x0c))
#define GPIOA_CRL *((volatile unsigned int*)(GPIOA_BASE+0x00))
#define GPIOA_CRH *((volatile unsigned int*)(GPIOA_BASE+0x04))
#define GPIOA_IDR *((volatile unsigned int*)(GPIOA_BASE+0x08))
#define GPIOA_ODR *((volatile unsigned int*)(GPIOA_BASE+0x0c))

//RCC registers
#define RCC_BASE 0x40021000

#define RCC_CR *((volatile unsigned int*)(RCC_BASE+0x00))
#define RCC_CFGR *((volatile unsigned int*)(RCC_BASE+0x04))
#define RCC_APB2ENR *((volatile unsigned int*) (RCC_BASE+0x18))

void clock_init()
{
	//enable clock for portA ,portB
	RCC_APB2ENR |= (0b11)<<2 ;
}

void GPIO_init()
{
	//PA.1 as input floating
	GPIOA_CRL =0x0;
	GPIOA_CRL |= (1<<6);

	//PB.1 as output push pull
	GPIOB_CRL = 0x0;
	GPIOB_CRL |= (1<<4);

	//PA.13 as input floating
	GPIOA_CRH =0x0;
	GPIOA_CRH |= (1<<22);

	//PB.13 as output push pull
	GPIOB_CRH = 0x0;
	GPIOB_CRH |= (1<<20);
}
void delay(int m)
{
	int i;
	for(i=0;i< m * 255;i++);
}

int main(void)
{
   clock_init();
   GPIO_init();
	while(1)
	{
		if(READ_bit(GPIOA_IDR,1) == 0)
		{
			Toggle_bit(GPIOB_ODR,1);
			while(READ_bit(GPIOA_IDR,1) == 0);
		}

		if(READ_bit(GPIOA_IDR,13) == 1)
		{
			Toggle_bit(GPIOB_ODR,13);

		}
		delay(2);

	}
}
